/**
 * The Cockpit mark is generated, not drawn.
 *
 *   node apps/desktop/scripts/logo.mjs
 *
 * A wordmark made of pixels only stays honest if the pixels are real: the
 * letterforms are a bitmap face (scripts/glyphs.mjs), run-length merged into
 * rectangles. Nothing is hand-placed, so the mark can be re-cut at any size —
 * or for any word — without a design tool, and `icon.mjs` cuts the Dock icon
 * from the same grid.
 *
 * Writes the two Vue brand components (theme-aware, currentColor) and the two
 * standalone SVGs used outside the app (README, packaging).
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROWS, LETTER_GAP, compose, runs } from './glyphs.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const app = resolve(here, '..')

function rects(cells, indent) {
  return runs(cells)
    .map(([x, y, w]) => `${indent}<rect x="${x}" y="${y}" width="${w}" height="1" />`)
    .join('\n')
}

/**
 * The mark, split into its two inks.
 *
 * The first letter carries its own ink so a placement can tint it: the C of
 * the wordmark and the C of the app icon are the same shape, and colouring it
 * apart is what says so. The cut runs down the middle of the first gap.
 */
function layers(word) {
  const { cells, spans, width } = compose(word)
  const cut = spans.length > 1 ? spans[0].x1 + Math.ceil(LETTER_GAP / 2) : Infinity
  const keys = [...cells]
  const lead = keys.filter((k) => Number(k.split(',')[0]) <= cut)
  const ink = keys.filter((k) => Number(k.split(',')[0]) > cut)

  const body = (indent, leadFill, inkFill) =>
    [
      `${indent}<g class="lead"${leadFill ? ` fill="${leadFill}"` : ''}>`,
      rects(lead, indent + '  '),
      `${indent}</g>`,
      ...(ink.length
        ? [
            `${indent}<g class="ink"${inkFill ? ` fill="${inkFill}"` : ''}>`,
            rects(ink, indent + '  '),
            `${indent}</g>`,
          ]
        : []),
    ].join('\n')

  /* The box is the ink and nothing else. Air around a logo is the caller's
     business — baked in, it becomes padding no margin can take back. */
  return { width, height: ROWS, body }
}

function vue(word, comment) {
  const l = layers(word)
  return `<script setup lang="ts">
import { computed } from 'vue'

/**
 * ${comment}
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this
 * file. Every pixel is a rect on a ${ROWS}-row grid, so the mark has one
 * silhouette at 18px and at 400px rather than a shape that dissolves as it
 * shrinks.
 *
 * The first letter is its own ink. It follows \`currentColor\` like the rest
 * until a placement sets \`--wm-lead\` — the two-tone wordmark is opt-in, so
 * the mark never arrives tinted somewhere it was only meant to be text.
 */
const props = withDefaults(defineProps<{ height?: number }>(), { height: ${ROWS * 3} })

/* Snapped to a whole multiple of the grid. A 2px stem at a fractional scale
   lands on a half pixel and the rounding eats one side of it — which is the
   difference between a pixel mark and a blurred one. */
const GRID = ${ROWS}
const h = computed(() => Math.max(GRID, Math.round(props.height / GRID) * GRID))
const w = computed(() => (h.value * ${l.width}) / GRID)
<\/script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    viewBox="0 0 ${l.width} ${l.height}"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="${word}"
  >
${l.body('    ')}
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
.lead {
  fill: var(--wm-lead, currentColor);
}
</style>
`
}

/* The standalone files are read outside the app, where no custom property
   resolves — so they carry the light-theme inks literally. */
const INK = '#5f5f6b'
const LEAD = '#5b58e0'

function svg(word) {
  const l = layers(word)
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${l.width * 8}" height="${l.height * 8}" viewBox="0 0 ${l.width} ${l.height}" fill="${INK}" shape-rendering="crispEdges">
${l.body('  ', LEAD, INK)}
</svg>
`
}

mkdirSync(resolve(app, 'src/components/brand'), { recursive: true })
mkdirSync(resolve(app, 'src/assets'), { recursive: true })

writeFileSync(
  resolve(app, 'src/components/brand/Wordmark.vue'),
  vue('COCKPIT', 'The full wordmark — used where the app introduces itself.'),
)
writeFileSync(
  resolve(app, 'src/components/brand/Mark.vue'),
  vue('C', 'The compact mark — the rail, the dock, anywhere the word will not fit.'),
)
writeFileSync(resolve(app, 'src/assets/wordmark.svg'), svg('COCKPIT'))
writeFileSync(resolve(app, 'src/assets/mark.svg'), svg('C'))

console.log('wrote Wordmark.vue, Mark.vue, wordmark.svg, mark.svg')
