/**
 * The Cockpit mark is generated, not drawn.
 *
 *   node apps/desktop/scripts/logo.mjs
 *
 * A wordmark made of pixels only stays honest if the pixels are real: the
 * letterforms are a bitmap face (scripts/glyphs.mjs), run-length merged into
 * rectangles. Nothing is hand-placed, so the mark can be re-cut at any size —
 * or for any word — without a design tool, and `icon.mjs` cuts the Dock icon
 * from the same grid.
 *
 * Writes the two Vue brand components (theme-aware, currentColor) and the two
 * standalone SVGs used outside the app (README, packaging), and the launch
 * splash into index.html.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROWS, LETTER_GAP, compose, runs } from './glyphs.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const app = resolve(here, '..')

function rects(cells, indent) {
  return runs(cells)
    .map(([x, y, w]) => `${indent}<rect x="${x}" y="${y}" width="${w}" height="1" />`)
    .join('\n')
}

/**
 * The mark, split into its two inks.
 *
 * The first letter carries its own ink so a placement can tint it: the C of
 * the wordmark and the C of the app icon are the same shape, and colouring it
 * apart is what says so. The cut runs down the middle of the first gap.
 */
function layers(word) {
  const { cells, spans, width } = compose(word)
  const cut = spans.length > 1 ? spans[0].x1 + Math.ceil(LETTER_GAP / 2) : Infinity
  const keys = [...cells]
  const lead = keys.filter((k) => Number(k.split(',')[0]) <= cut)
  const ink = keys.filter((k) => Number(k.split(',')[0]) > cut)

  const body = (indent, leadFill, inkFill) =>
    [
      `${indent}<g class="lead"${leadFill ? ` fill="${leadFill}"` : ''}>`,
      rects(lead, indent + '  '),
      `${indent}</g>`,
      ...(ink.length
        ? [
            `${indent}<g class="ink"${inkFill ? ` fill="${inkFill}"` : ''}>`,
            rects(ink, indent + '  '),
            `${indent}</g>`,
          ]
        : []),
    ].join('\n')

  /* The box is the ink and nothing else. Air around a logo is the caller's
     business — baked in, it becomes padding no margin can take back. */
  return { width, height: ROWS, body }
}

function vue(word, comment) {
  const l = layers(word)
  return `<script setup lang="ts">
import { computed } from 'vue'

/**
 * ${comment}
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this
 * file. Every pixel is a rect on a ${ROWS}-row grid, so the mark has one
 * silhouette at 18px and at 400px rather than a shape that dissolves as it
 * shrinks.
 *
 * The first letter is its own ink. It follows \`currentColor\` like the rest
 * until a placement sets \`--wm-lead\` — the two-tone wordmark is opt-in, so
 * the mark never arrives tinted somewhere it was only meant to be text.
 */
const props = withDefaults(defineProps<{ height?: number }>(), { height: ${ROWS * 3} })

/* Snapped to a whole multiple of the grid. A 2px stem at a fractional scale
   lands on a half pixel and the rounding eats one side of it — which is the
   difference between a pixel mark and a blurred one. */
const GRID = ${ROWS}
const h = computed(() => Math.max(GRID, Math.round(props.height / GRID) * GRID))
const w = computed(() => (h.value * ${l.width}) / GRID)
<\/script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    viewBox="0 0 ${l.width} ${l.height}"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="${word}"
  >
${l.body('    ')}
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
.lead {
  fill: var(--wm-lead, currentColor);
}
</style>
`
}

/* The standalone files are read outside the app, where no custom property
   resolves — so they carry the light-theme inks literally. These are the
   light values of `--brand-ink` and `--accent`; change one and change the
   other. */
const INK = '#8c8c9c'
const LEAD = '#5b58e0'

function svg(word) {
  const l = layers(word)
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${l.width * 8}" height="${l.height * 8}" viewBox="0 0 ${l.width} ${l.height}" fill="${INK}" shape-rendering="crispEdges">
${l.body('  ', LEAD, INK)}
</svg>
`
}

/**
 * The launch splash — the C, one rect per cell, and a comet of accent that
 * traces the letter from its top terminal round to its bottom one while the
 * window waits for the core.
 *
 * Written into index.html rather than mounted by Vue: the window is shown on
 * its first paint, and the first paint happens long before the bundle, the
 * fonts and the daemon's first answer. Static markup is the only thing that is
 * already there. `src/core/splash.ts` lets it go.
 *
 * Every cell is its own rect (no run merging) because every cell is lit on its
 * own beat. `--p` is where the cell sits along the stroke, 0 at the top
 * terminal and 1 at the bottom one, measured as the angle round the letter's
 * centre — which for a C is the path a pen would take.
 */
function splash() {
  const { cells, width } = compose('C')
  const cx = (width - 1) / 2
  const cy = (ROWS - 1) / 2
  const pts = [...cells].map((k) => {
    const [x, y] = k.split(',').map(Number)
    const a = Math.atan2(y - cy, x - cx)
    // Counter-clockwise from the top terminal, through the left, to the bottom.
    return { x, y, t: a <= 0 ? -a : 2 * Math.PI - a }
  })
  const lo = Math.min(...pts.map((p) => p.t))
  const hi = Math.max(...pts.map((p) => p.t))
  const mark = pts
    .sort((a, b) => a.t - b.t)
    .map(
      (p) =>
        `        <rect x="${p.x}" y="${p.y}" width="1" height="1" style="--p:${((p.t - lo) / (hi - lo)).toFixed(3)}" />`,
    )
    .join('\n')
  const word = layers('COCKPIT')

  /* Literal inks, not tokens: tokens.css arrives with the bundle, and this is
     painted before it. Same values as --bg, --brand-ink and --accent. */
  return `<style>
      :root { color-scheme: light dark; }
      #splash {
        --bg: light-dark(#f2f2f6, #0c0c10);
        --ink: light-dark(#8c8c9c, #c9cad5);
        --hot: light-dark(#5b58e0, #8b88ff);
        --rest: light-dark(rgba(140, 140, 156, 0.2), rgba(201, 202, 213, 0.12));
        position: fixed;
        inset: 0;
        z-index: 10000;
        display: grid;
        place-content: center;
        justify-items: center;
        gap: 36px;
        background: var(--bg);
        /* The window has no title bar; while this covers it, it is the handle. */
        -webkit-app-region: drag;
        transition: opacity 320ms cubic-bezier(0.4, 0, 0.2, 1);
      }
      #splash svg { display: block; overflow: visible; }
      #splash .c { animation: splash-in 420ms cubic-bezier(0.32, 0.72, 0, 1) backwards; }
      #splash .c rect {
        fill: var(--rest);
        /* 1.2s round the letter, then a breath before the next pass. */
        animation: splash-trace 1.8s linear calc(var(--p) * 1.2s + 240ms) infinite;
      }
      #splash .w { fill: var(--ink); opacity: 0; animation: splash-word 600ms ease 200ms forwards; }
      @keyframes splash-in { from { opacity: 0; transform: scale(0.94); } }
      @keyframes splash-word { to { opacity: 0.55; } }
      @keyframes splash-trace {
        0% { fill: var(--hot); animation-timing-function: cubic-bezier(0.3, 0, 0.7, 1); }
        45%, 100% { fill: var(--rest); }
      }
      /* Ready: the letter fills along the same path, then everything goes. */
      #splash.done .c rect { animation: splash-fill 260ms ease-out calc(var(--p) * 200ms) forwards; }
      @keyframes splash-fill { to { fill: var(--hot); } }
      #splash.gone { opacity: 0; }
      #splash.gone .c { transform: scale(1.06); transition: transform 320ms cubic-bezier(0.4, 0, 1, 1); }
      /* Out-specifies base.css's global 0.01ms, which on an infinite animation is a strobe. */
      @media (prefers-reduced-motion: reduce) {
        #splash .c rect { animation: none !important; fill: var(--hot); }
      }
    </style>
    <div id="splash" aria-hidden="true">
      <svg class="c" width="${width * 8}" height="${ROWS * 8}" viewBox="0 0 ${width} ${ROWS}" shape-rendering="crispEdges">
${mark}
      </svg>
      <svg class="w" width="${word.width * 2}" height="${ROWS * 2}" viewBox="0 0 ${word.width} ${ROWS}" shape-rendering="crispEdges">
${word.body('        ')}
      </svg>
    </div>`
}

const INDEX = resolve(app, 'index.html')
const BEGIN = '<!-- splash: generated by scripts/logo.mjs -->'
const END = '<!-- /splash -->'
const html = readFileSync(INDEX, 'utf8')
const from = html.indexOf(BEGIN)
const to = html.indexOf(END)
if (from < 0 || to < 0) throw new Error('index.html has lost its splash markers')
writeFileSync(INDEX, html.slice(0, from + BEGIN.length) + '\n    ' + splash() + '\n    ' + html.slice(to))

mkdirSync(resolve(app, 'src/components/brand'), { recursive: true })
mkdirSync(resolve(app, 'src/assets'), { recursive: true })

writeFileSync(
  resolve(app, 'src/components/brand/Wordmark.vue'),
  vue('COCKPIT', 'The full wordmark — used where the app introduces itself.'),
)
writeFileSync(
  resolve(app, 'src/components/brand/Mark.vue'),
  vue('C', 'The compact mark — the rail, the dock, anywhere the word will not fit.'),
)
writeFileSync(resolve(app, 'src/assets/wordmark.svg'), svg('COCKPIT'))
writeFileSync(resolve(app, 'src/assets/mark.svg'), svg('C'))

console.log('wrote Wordmark.vue, Mark.vue, wordmark.svg, mark.svg, the splash in index.html')
