const { app, BrowserWindow, dialog, ipcMain, shell, nativeTheme } = require('electron')
const { execFileSync, spawn } = require('node:child_process')
const { dirname, join, resolve } = require('node:path')
const { existsSync } = require('node:fs')
const { createConnection } = require('node:net')
const { startUpdater } = require('./updater.cjs')

/**
 * §13 — "Le noyau tourne en permanence, indépendamment de l'interface."
 * Electron's main process is NOT the core. It only makes sure a core exists
 * and opens a window pointed at it; closing the window kills neither the dev
 * servers nor the agents.
 *
 * CommonJS on purpose: Electron's ESM entry path is still fragile, and this
 * file is pure plumbing with nothing to gain from modules.
 */

const DEV = !app.isPackaged
const CORE_PORT = Number(process.env.COCKPIT_PORT || 7717)

/**
 * The Dock tile. Generated by `pnpm --filter @cockpit/desktop icon` from the
 * same grid as the mark in the rail (apps/desktop/scripts/icon.mjs).
 *
 * A packaged app takes its icon from the bundle's Info.plist — build/icon.icns
 * beside this file. Unpackaged there is no bundle of ours to read, so macOS
 * shows Electron's own icon and there is nothing CSS can do about it: the Dock
 * is not the window. `app.dock.setIcon` is the one way to say otherwise.
 */
const ICON = resolve(__dirname, '..', 'build', 'icon.png')

function probeCore(port) {
  return new Promise((res) => {
    const sock = createConnection({ host: '127.0.0.1', port })
    const done = (v) => {
      sock.destroy()
      res(v)
    }
    sock.once('connect', () => done(true))
    sock.once('error', () => done(false))
    setTimeout(() => done(false), 800)
  })
}

/**
 * How to start a core, which is two questions: what runs it, and what it runs.
 *
 * The first answer is the same in both modes and it is not a convenience —
 * `process.execPath` is Electron, and `ELECTRON_RUN_AS_NODE` makes it behave as
 * the Node it embeds. The core loads better-sqlite3, a compiled module that
 * binds to one ABI: Electron 33 embeds Node 20 (ABI 130) while a developer's
 * shell is on Node 22 (ABI 127), and a module built for either is refused by
 * the other. Running the core under the same binary that runs this file means
 * there is one ABI to build for instead of two, and a packaged app that needs
 * no Node installed on the machine at all.
 *
 * The second answer is what differs. Packaged there is no repository and no
 * TypeScript: the core is one bundled ESM file built by scripts/bundle-core.mjs.
 * Unpackaged it is still the source tree, run through tsx, so editing the core
 * stays a matter of saving a file.
 */
function coreLauncher() {
  if (!DEV) {
    // Shipped unpacked rather than inside the asar: the archive is not a
    // filesystem, and the native modules this file loads have to be real paths
    // the dynamic loader can open (electron-builder's `asarUnpack`).
    const bundle = resolve(__dirname, '..', 'resources', 'core.mjs')
    return existsSync(bundle) ? { args: [bundle], what: bundle } : null
  }
  const entry = resolve(__dirname, '..', '..', '..', 'packages', 'core', 'src', 'index.ts')
  if (!existsSync(entry)) return null
  // tsx's CLI rather than the `tsx` shim on PATH: the shim is a Node script, so
  // it would start a second runtime — the wrong one — to launch the right one.
  // Read through the package's own `bin` rather than reaching for dist/cli.mjs:
  // tsx does not export that subpath, and `require.resolve` honours `exports`.
  let tsx
  try {
    const manifest = require.resolve('tsx/package.json', { paths: [resolve(__dirname, '..')] })
    tsx = resolve(dirname(manifest), require(manifest).bin)
  } catch {
    return null
  }
  if (!existsSync(tsx)) return null
  return { args: [tsx, entry], what: entry }
}

async function ensureCore() {
  if (await probeCore(CORE_PORT)) {
    console.log('[cockpit] core already running on ' + CORE_PORT)
    return
  }
  const launcher = coreLauncher()
  if (!launcher) {
    console.error('[cockpit] no core to start (' + (DEV ? 'dev' : 'packaged') + ')')
    return
  }
  // Detached: the core outlives this window, and this app on quit.
  const child = spawn(process.execPath, launcher.args, {
    detached: true,
    stdio: 'ignore',
    env: Object.assign({}, process.env, {
      COCKPIT_PORT: String(CORE_PORT),
      ELECTRON_RUN_AS_NODE: '1',
    }),
  })
  child.unref()
  for (let i = 0; i < 40; i++) {
    if (await probeCore(CORE_PORT)) return
    await new Promise((r) => setTimeout(r, 250))
  }
  console.error('[cockpit] core did not come up in time')
}

/**
 * The three verbs behind the drawn traffic lights. Fire-and-forget on purpose:
 * a window button that awaited a round trip would feel like a button that did
 * not take.
 */
const senderWindow = (e) => BrowserWindow.fromWebContents(e.sender)
ipcMain.on('window:close', (e) => senderWindow(e)?.close())
ipcMain.on('window:minimize', (e) => senderWindow(e)?.minimize())
ipcMain.on('window:zoom', (e, alt) => {
  const win = senderWindow(e)
  if (!win) return
  // Same split as the button it replaces: green is fullscreen, ⌥-green is the
  // older zoom-to-fit.
  if (alt) (win.isMaximized() ? win.unmaximize() : win.maximize())
  else win.setFullScreen(!win.isFullScreen())
})

/**
 * The one thing the renderer genuinely cannot do for itself. §13 rule 1 keeps
 * the bridge tiny, but `window.prompt` does not exist in Electron at all, so
 * "add a project" needs a real dialog or it is a button that throws.
 */
ipcMain.handle('dialog:pickFolder', async (event, opts) => {
  const win = BrowserWindow.fromWebContents(event.sender)
  // Read field by field rather than spread: the renderer is the untrusted side
  // of this bridge, and `showOpenDialog` takes options that are not its business.
  const o = opts && typeof opts === 'object' ? opts : {}
  const str = (v, fallback) => (typeof v === 'string' && v ? v : fallback)
  const res = await dialog.showOpenDialog(win, {
    title: str(o.title, 'Add a project'),
    message: str(o.message, 'Pick the folder Cockpit should watch'),
    buttonLabel: str(o.buttonLabel, 'Add'),
    ...(typeof o.defaultPath === 'string' && o.defaultPath ? { defaultPath: o.defaultPath } : {}),
    properties: ['openDirectory', 'createDirectory'],
  })
  return res.canceled ? null : (res.filePaths[0] ?? null)
})

/**
 * §13 — `ensureCore` only ran at launch, so a core stopped mid-session stayed
 * stopped until the app was quit and reopened. That is the one thing the
 * renderer cannot do for itself: it has no child processes (rule 1).
 */
ipcMain.handle('core:restart', async () => {
  // The core is asked to stop over its own socket before this point; wait for
  // the port to clear so `ensureCore` does not adopt the dying one.
  for (let i = 0; i < 40; i++) {
    if (!(await probeCore(CORE_PORT))) break
    await new Promise((r) => setTimeout(r, 250))
  }
  // Still bound: the graceful ask never landed. That is precisely the case
  // this button exists for — a core the window refuses to talk to (protocol
  // mismatch) cannot be asked to stop over the socket it just hung up, and a
  // restart that adopts the very process it was meant to replace is not a
  // restart. Fall back to the port's owner.
  if (await probeCore(CORE_PORT)) killPort(CORE_PORT)
  for (let i = 0; i < 20; i++) {
    if (!(await probeCore(CORE_PORT))) break
    await new Promise((r) => setTimeout(r, 250))
  }
  await ensureCore()
  return probeCore(CORE_PORT)
})

/**
 * Whatever is listening on the core's port, stopped. Deliberately narrow: one
 * port, ours, and SIGTERM first so the core runs its own shutdown. Best
 * effort — no lsof, no permission, nothing happens and `ensureCore` reports
 * the port still bound.
 */
function killPort(port) {
  let pids = []
  try {
    pids = execFileSync('lsof', ['-nP', '-iTCP:' + port, '-sTCP:LISTEN', '-t'], { encoding: 'utf8' })
      .split('\n')
      .map((l) => Number(l.trim()))
      .filter((n) => Number.isInteger(n) && n > 0 && n !== process.pid)
  } catch {
    return
  }
  for (const pid of pids) {
    try {
      process.kill(pid, 'SIGTERM')
    } catch {
      /* already gone */
    }
  }
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 960,
    minHeight: 600,
    show: false,
    // Raycast-style chrome: the traffic lights float over the rail.
    titleBarStyle: 'hiddenInset',
    // Where the native buttons would sit, kept in step with the CSS that draws
    // them now (TrafficLights.vue): 10px in from the left of the 72px rail
    // (--rail-w), 19px down so the 12px buttons centre in the 50px band.
    trafficLightPosition: { x: 10, y: 19 },
    // The frame the window is painted before the renderer has anything to
    // show. Kept equal to --bg in src/styles/tokens.css, or launch flashes a
    // shade the app never uses again.
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#0c0c10' : '#f2f2f6',
    // Ignored on macOS, where the icon belongs to the bundle rather than to
    // the window; this is what Windows and Linux draw in the title bar.
    ...(existsSync(ICON) ? { icon: ICON } : {}),
    webPreferences: {
      preload: join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  })

  // AppKit greys the standard window buttons whenever the window is not the
  // key window, and exposes no way to ask it not to — the state belongs to the
  // window, not to the buttons. Hiding them and drawing three of our own in the
  // renderer is the only way they stay lit, and it costs the IPC below.
  if (process.platform === 'darwin') win.setWindowButtonVisibility(false)

  win.once('ready-to-show', () => win.show())

  // §13 rule 1 — external links leave the app rather than navigating it.
  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  if (DEV) {
    win.loadURL('http://127.0.0.1:5273')
  } else {
    win.loadFile(join(__dirname, '..', 'dist', 'index.html'))
  }
  return win
}

app.whenReady().then(async () => {
  if (process.platform === 'darwin' && DEV && existsSync(ICON)) app.dock?.setIcon(ICON)
  await ensureCore()
  createWindow()
  // Given a getter rather than the window: the one it should parent its dialog
  // to is whichever exists when an update lands, which is not this one.
  startUpdater(() => BrowserWindow.getAllWindows()[0] ?? null)
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
