const { app, BrowserWindow, dialog, ipcMain, shell, nativeTheme } = require('electron')
const { execFileSync, spawn } = require('node:child_process')
const { dirname, join, resolve } = require('node:path')
const { appendFileSync, closeSync, copyFileSync, existsSync, mkdirSync, openSync, readSync, renameSync, statSync } = require('node:fs')
const { homedir } = require('node:os')
const { format } = require('node:util')
const { createConnection } = require('node:net')
const { startUpdater } = require('./updater.cjs')

/**
 * §13 — "Le noyau tourne en permanence, indépendamment de l'interface."
 * Electron's main process is NOT the core. It only makes sure a core exists
 * and opens a window pointed at it; closing the window kills neither the dev
 * servers nor the agents.
 *
 * CommonJS on purpose: Electron's ESM entry path is still fragile, and this
 * file is pure plumbing with nothing to gain from modules.
 */

const DEV = !app.isPackaged

/**
 * Two services, never one. `pnpm dev` and the installed app used to share
 * ~/.cockpit *and* port 7717, and since whichever window opens second adopts
 * the service already listening, the installed app could be talking to a
 * service run from the source tree — or `pnpm dev` to last week's release —
 * with nothing on screen to say so. Development gets its own port and its
 * own data. Either can still be pointed elsewhere with the two variables.
 */
const CORE_PORT = Number(process.env.COCKPIT_PORT || (DEV ? 7718 : 7717))
const HOME = process.env.COCKPIT_HOME || join(homedir(), DEV ? '.cockpit-dev' : '.cockpit')
const LOGS = join(HOME, 'logs')
const CORE_LOG = join(LOGS, 'core.log')
const APP_LOG = join(LOGS, 'app.log')

/**
 * A first development run starts from the installed app's list of projects
 * rather than from nothing — the config only, which is paths and settings.
 * The database is not copied: conversations and the journal are what the two
 * are being kept apart for.
 */
function seedDevHome() {
  if (!DEV || process.env.COCKPIT_HOME || existsSync(HOME)) return
  mkdirSync(HOME, { recursive: true })
  const from = join(homedir(), '.cockpit', 'config.json')
  try {
    if (existsSync(from)) copyFileSync(from, join(HOME, 'config.json'))
  } catch {
    /* an empty dev home is still a working one */
  }
}

/** Keeps one previous generation, so a file never grows without end. */
function rotate(file) {
  try {
    if (existsSync(file) && statSync(file).size > 5 * 1024 * 1024) renameSync(file, file + '.1')
  } catch {
    /* rotation is a nicety */
  }
}

/**
 * This process's own output, kept. A packaged app has no terminal to print
 * to, so without this every `console.error` below went nowhere. Still printed
 * as well: `pnpm dev` reads it in the terminal.
 */
function captureAppLog() {
  try {
    mkdirSync(LOGS, { recursive: true })
    rotate(APP_LOG)
  } catch {
    return
  }
  for (const level of ['log', 'warn', 'error']) {
    const original = console[level].bind(console)
    console[level] = (...args) => {
      original(...args)
      try {
        appendFileSync(APP_LOG, new Date().toISOString() + ' ' + level.padEnd(5) + ' ' + format(...args) + '\n')
      } catch {
        /* a full disk is not a reason to stop the app */
      }
    }
  }
}

/** The last `bytes` of a file, starting at a whole line. */
function tailFile(file, bytes) {
  if (!existsSync(file)) return { path: file, text: '', size: 0, missing: true }
  const size = statSync(file).size
  const from = Math.max(0, size - bytes)
  const buf = Buffer.alloc(size - from)
  const fd = openSync(file, 'r')
  try {
    readSync(fd, buf, 0, buf.length, from)
  } finally {
    closeSync(fd)
  }
  let text = buf.toString('utf8')
  if (from > 0) text = text.slice(text.indexOf('\n') + 1)
  return { path: file, text, size, missing: false }
}

/**
 * The Dock tile. Generated by `pnpm --filter @cockpit/desktop icon` from the
 * same grid as the mark in the rail (apps/desktop/scripts/icon.mjs).
 *
 * A packaged app takes its icon from the bundle's Info.plist — build/icon.icns
 * beside this file. Unpackaged there is no bundle of ours to read, so macOS
 * shows Electron's own icon and there is nothing CSS can do about it: the Dock
 * is not the window. `app.dock.setIcon` is the one way to say otherwise.
 */
const ICON = resolve(__dirname, '..', 'build', 'icon.png')

function probeCore(port) {
  return new Promise((res) => {
    const sock = createConnection({ host: '127.0.0.1', port })
    const done = (v) => {
      sock.destroy()
      res(v)
    }
    sock.once('connect', () => done(true))
    sock.once('error', () => done(false))
    setTimeout(() => done(false), 800)
  })
}

/**
 * How to start a core, which is two questions: what runs it, and what it runs.
 *
 * The first answer is the same in both modes and it is not a convenience —
 * `process.execPath` is Electron, and `ELECTRON_RUN_AS_NODE` makes it behave as
 * the Node it embeds. The core loads better-sqlite3, a compiled module that
 * binds to one ABI: Electron 33 embeds Node 20 (ABI 130) while a developer's
 * shell is on Node 22 (ABI 127), and a module built for either is refused by
 * the other. Running the core under the same binary that runs this file means
 * there is one ABI to build for instead of two, and a packaged app that needs
 * no Node installed on the machine at all.
 *
 * The second answer is what differs. Packaged there is no repository and no
 * TypeScript: the core is one bundled ESM file built by scripts/bundle-core.mjs.
 * Unpackaged it is still the source tree, run through tsx, so editing the core
 * stays a matter of saving a file.
 */
function coreLauncher() {
  if (!DEV) {
    // Shipped unpacked rather than inside the asar: the archive is not a
    // filesystem, and the native modules this file loads have to be real paths
    // the dynamic loader can open (electron-builder's `asarUnpack`).
    const bundle = resolve(__dirname, '..', 'resources', 'core.mjs')
    return existsSync(bundle) ? { args: [bundle], what: bundle } : null
  }
  const entry = resolve(__dirname, '..', '..', '..', 'packages', 'core', 'src', 'index.ts')
  if (!existsSync(entry)) return null
  // tsx's CLI rather than the `tsx` shim on PATH: the shim is a Node script, so
  // it would start a second runtime — the wrong one — to launch the right one.
  // Read through the package's own `bin` rather than reaching for dist/cli.mjs:
  // tsx does not export that subpath, and `require.resolve` honours `exports`.
  let tsx
  try {
    const manifest = require.resolve('tsx/package.json', { paths: [resolve(__dirname, '..')] })
    tsx = resolve(dirname(manifest), require(manifest).bin)
  } catch {
    return null
  }
  if (!existsSync(tsx)) return null
  return { args: [tsx, entry], what: entry }
}

/**
 * The PATH a terminal would have. An app opened from the Dock or Finder is
 * started by launchd with /usr/bin:/bin:/usr/sbin:/sbin and nothing else, and
 * the core hands that to every process it starts — so `claude` in
 * ~/.local/bin, `pnpm` and `node` from Homebrew or a version manager, all read
 * as missing. `npm run dev` never showed it because a terminal passes its own.
 *
 * Asked of the login shell rather than guessed, since where those binaries
 * live is the user's setup. The markers keep whatever an rc file prints out of
 * the value. Windows GUI apps get the user's PATH already.
 */
function shellPath() {
  if (process.platform === 'win32') return process.env.PATH
  const MARK = '__COCKPIT_PATH__'
  try {
    const out = execFileSync(
      process.env.SHELL || '/bin/zsh',
      ['-ilc', 'printf "' + MARK + '%s' + MARK + '" "$PATH"'],
      { encoding: 'utf8', timeout: 5000, stdio: ['ignore', 'pipe', 'ignore'] },
    )
    const found = out.split(MARK)[1]
    if (found) return found
  } catch {
    /* a shell that hangs or fails: fall through to the usual places */
  }
  return [join(homedir(), '.local', 'bin'), '/opt/homebrew/bin', '/usr/local/bin', process.env.PATH]
    .filter(Boolean)
    .join(':')
}

/**
 * Where the core writes. It is detached from this process, so its stdout has
 * nowhere else to go, and a core that fails silently is one nobody can help.
 */
function coreLog() {
  try {
    mkdirSync(LOGS, { recursive: true })
    rotate(CORE_LOG)
    return openSync(CORE_LOG, 'a')
  } catch {
    return 'ignore'
  }
}

async function ensureCore() {
  if (await probeCore(CORE_PORT)) {
    console.log('[cockpit] core already running on ' + CORE_PORT)
    return
  }
  const launcher = coreLauncher()
  if (!launcher) {
    console.error('[cockpit] no core to start (' + (DEV ? 'dev' : 'packaged') + ')')
    return
  }
  // Detached: the core outlives this window, and this app on quit.
  const log = coreLog()
  const child = spawn(process.execPath, launcher.args, {
    detached: true,
    stdio: ['ignore', log, log],
    env: Object.assign({}, process.env, {
      COCKPIT_PORT: String(CORE_PORT),
      COCKPIT_HOME: HOME,
      // What the service reports as its version, so a window can tell that the
      // service it adopted was started by an older app.
      COCKPIT_APP_VERSION: app.getVersion(),
      COCKPIT_BUILD: DEV ? 'source' : 'packaged',
      ELECTRON_RUN_AS_NODE: '1',
      // Packaged only: a dev launch comes from a terminal that already has it.
      ...(DEV ? {} : { PATH: shellPath() }),
    }),
  })
  child.unref()
  // The child holds its own copy of the descriptor.
  if (typeof log === 'number') closeSync(log)
  console.log('[cockpit] started a service on ' + CORE_PORT + ' (pid ' + child.pid + ', ' + HOME + ')')
  for (let i = 0; i < 40; i++) {
    if (await probeCore(CORE_PORT)) return
    await new Promise((r) => setTimeout(r, 250))
  }
  console.error('[cockpit] core did not come up in time')
}

/**
 * The three verbs behind the drawn traffic lights. Fire-and-forget on purpose:
 * a window button that awaited a round trip would feel like a button that did
 * not take.
 */
const senderWindow = (e) => BrowserWindow.fromWebContents(e.sender)
ipcMain.on('window:close', (e) => senderWindow(e)?.close())
ipcMain.on('window:minimize', (e) => senderWindow(e)?.minimize())
ipcMain.on('window:zoom', (e, alt) => {
  const win = senderWindow(e)
  if (!win) return
  // Same split as the button it replaces: green is fullscreen, ⌥-green is the
  // older zoom-to-fit.
  if (alt) (win.isMaximized() ? win.unmaximize() : win.maximize())
  else win.setFullScreen(!win.isFullScreen())
})

/**
 * The one thing the renderer genuinely cannot do for itself. §13 rule 1 keeps
 * the bridge tiny, but `window.prompt` does not exist in Electron at all, so
 * "add a project" needs a real dialog or it is a button that throws.
 */
ipcMain.handle('dialog:pickFolder', async (event, opts) => {
  const win = BrowserWindow.fromWebContents(event.sender)
  // Read field by field rather than spread: the renderer is the untrusted side
  // of this bridge, and `showOpenDialog` takes options that are not its business.
  const o = opts && typeof opts === 'object' ? opts : {}
  const str = (v, fallback) => (typeof v === 'string' && v ? v : fallback)
  const res = await dialog.showOpenDialog(win, {
    title: str(o.title, 'Add a project'),
    message: str(o.message, 'Pick the folder Cockpit should watch'),
    buttonLabel: str(o.buttonLabel, 'Add'),
    ...(typeof o.defaultPath === 'string' && o.defaultPath ? { defaultPath: o.defaultPath } : {}),
    properties: ['openDirectory', 'createDirectory'],
  })
  return res.canceled ? null : (res.filePaths[0] ?? null)
})

/**
 * What the Service sheet knows that the service cannot tell it: which app this
 * window is, and where it expects the service to be. The comparison between
 * the two versions is the point — the service outlives an update.
 */
ipcMain.handle('host:info', () => ({
  version: app.getVersion(),
  build: DEV ? 'source' : 'packaged',
  port: CORE_PORT,
  home: HOME,
  appLog: APP_LOG,
  coreLog: CORE_LOG,
  electron: process.versions.electron,
  platform: process.platform,
}))

ipcMain.handle('host:appLog', (_e, bytes) => {
  const n = Number.isFinite(bytes) ? Math.min(Math.max(bytes, 1_000), 1_000_000) : 64_000
  return tailFile(APP_LOG, n)
})

/** Only ever the logs folder: the renderer does not get to name a path. */
ipcMain.handle('host:revealLogs', () => {
  mkdirSync(LOGS, { recursive: true })
  return shell.openPath(LOGS)
})

/**
 * §13 — `ensureCore` only ran at launch, so a core stopped mid-session stayed
 * stopped until the app was quit and reopened. That is the one thing the
 * renderer cannot do for itself: it has no child processes (rule 1).
 */
ipcMain.handle('core:restart', async () => {
  // The core is asked to stop over its own socket before this point; wait for
  // the port to clear so `ensureCore` does not adopt the dying one.
  for (let i = 0; i < 40; i++) {
    if (!(await probeCore(CORE_PORT))) break
    await new Promise((r) => setTimeout(r, 250))
  }
  // Still bound: the graceful ask never landed. That is precisely the case
  // this button exists for — a core the window refuses to talk to (protocol
  // mismatch) cannot be asked to stop over the socket it just hung up, and a
  // restart that adopts the very process it was meant to replace is not a
  // restart. Fall back to the port's owner.
  if (await probeCore(CORE_PORT)) killPort(CORE_PORT)
  for (let i = 0; i < 20; i++) {
    if (!(await probeCore(CORE_PORT))) break
    await new Promise((r) => setTimeout(r, 250))
  }
  await ensureCore()
  return probeCore(CORE_PORT)
})

/**
 * Whatever is listening on the core's port, stopped. Deliberately narrow: one
 * port, ours, and SIGTERM first so the core runs its own shutdown. Best
 * effort — no lsof, no permission, nothing happens and `ensureCore` reports
 * the port still bound.
 */
function killPort(port) {
  let pids = []
  try {
    pids = execFileSync('lsof', ['-nP', '-iTCP:' + port, '-sTCP:LISTEN', '-t'], { encoding: 'utf8' })
      .split('\n')
      .map((l) => Number(l.trim()))
      .filter((n) => Number.isInteger(n) && n > 0 && n !== process.pid)
  } catch {
    return
  }
  for (const pid of pids) {
    try {
      process.kill(pid, 'SIGTERM')
    } catch {
      /* already gone */
    }
  }
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 960,
    minHeight: 600,
    show: false,
    // Raycast-style chrome: the traffic lights float over the rail.
    titleBarStyle: 'hiddenInset',
    // Where the native buttons would sit, kept in step with the CSS that draws
    // them now (TrafficLights.vue): 10px in from the left of the 72px rail
    // (--rail-w), 19px down so the 12px buttons centre in the 50px band.
    trafficLightPosition: { x: 10, y: 19 },
    // The frame the window is painted before the renderer has anything to
    // show. Kept equal to --bg in src/styles/tokens.css, or launch flashes a
    // shade the app never uses again.
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#0c0c10' : '#f2f2f6',
    // Ignored on macOS, where the icon belongs to the bundle rather than to
    // the window; this is what Windows and Linux draw in the title bar.
    ...(existsSync(ICON) ? { icon: ICON } : {}),
    webPreferences: {
      preload: join(__dirname, 'preload.cjs'),
      // The preload cannot read this process's constants, and the port is no
      // longer one number: it depends on how the app was started.
      additionalArguments: ['--cockpit-port=' + CORE_PORT],
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  })

  // AppKit greys the standard window buttons whenever the window is not the
  // key window, and exposes no way to ask it not to — the state belongs to the
  // window, not to the buttons. Hiding them and drawing three of our own in the
  // renderer is the only way they stay lit, and it costs the IPC below.
  if (process.platform === 'darwin') win.setWindowButtonVisibility(false)

  win.once('ready-to-show', () => win.show())

  // §13 rule 1 — external links leave the app rather than navigating it.
  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  if (DEV) {
    win.loadURL('http://127.0.0.1:5273')
  } else {
    win.loadFile(join(__dirname, '..', 'dist', 'index.html'))
  }
  return win
}

// Seeded first: it only runs when the folder does not exist yet, and opening
// the app log is what creates it.
seedDevHome()
captureAppLog()
process.on('uncaughtException', (e) => console.error('[cockpit] uncaught: ' + (e?.stack ?? e)))

app.whenReady().then(async () => {
  console.log('[cockpit] ' + app.getVersion() + ' (' + (DEV ? 'source' : 'packaged') + ') starting, service port ' + CORE_PORT)
  if (process.platform === 'darwin' && DEV && existsSync(ICON)) app.dock?.setIcon(ICON)
  await ensureCore()
  createWindow()
  // Given a getter rather than the window: the one it should parent its dialog
  // to is whichever exists when an update lands, which is not this one.
  startUpdater(() => BrowserWindow.getAllWindows()[0] ?? null)
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
