<script setup lang="ts">
import { computed } from 'vue'

/**
 * The compact mark — the rail, the dock, anywhere the word will not fit.
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this
 * file. Every pixel is a rect on a 12-row grid, so the mark has one
 * silhouette at 18px and at 400px rather than a shape that dissolves as it
 * shrinks.
 *
 * The first letter is its own ink. It follows `currentColor` like the rest
 * until a placement sets `--wm-lead` — the two-tone wordmark is opt-in, so
 * the mark never arrives tinted somewhere it was only meant to be text.
 */
const props = withDefaults(defineProps<{ height?: number }>(), { height: 36 })

/* Snapped to a whole multiple of the grid. A 2px stem at a fractional scale
   lands on a half pixel and the rounding eats one side of it — which is the
   difference between a pixel mark and a blurred one. */
const GRID = 12
const h = computed(() => Math.max(GRID, Math.round(props.height / GRID) * GRID))
const w = computed(() => (h.value * 9) / GRID)
</script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    viewBox="0 0 9 12"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="C"
  >
    <g class="lead">
      <rect x="1" y="0" width="7" height="1" />
      <rect x="0" y="1" width="9" height="1" />
      <rect x="0" y="2" width="9" height="1" />
      <rect x="0" y="3" width="4" height="1" />
      <rect x="0" y="4" width="3" height="1" />
      <rect x="0" y="5" width="3" height="1" />
      <rect x="0" y="6" width="3" height="1" />
      <rect x="0" y="7" width="3" height="1" />
      <rect x="0" y="8" width="4" height="1" />
      <rect x="0" y="9" width="9" height="1" />
      <rect x="0" y="10" width="9" height="1" />
      <rect x="1" y="11" width="7" height="1" />
    </g>
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
.lead {
  fill: var(--wm-lead, currentColor);
}
</style>
