<script setup lang="ts">
import { computed } from 'vue'

/**
 * The compact mark — the rail, the dock, anywhere the word will not fit.
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this file.
 * Every pixel is a rect on a 12-row grid; the fringe is an ordered dither,
 * so the mark stays itself at 14px and at 400px.
 *
 * `crisp` drops the dither and trims to the letterform. Use it anywhere the
 * mark is small: the fringe needs three or four device pixels per grid cell to
 * read as a fringe, and below that it only softens the stroke.
 */
const props = withDefaults(defineProps<{ height?: number; crisp?: boolean }>(), {
  height: 26,
  crisp: false,
})

/* Crisp only pays off on a whole multiple of the grid — a 2px stem at a
   fractional scale lands on a half pixel and the rounding eats one side of it. */
const INK_ROWS = 9
const h = computed(() =>
  props.crisp ? Math.max(INK_ROWS, Math.round(props.height / INK_ROWS) * INK_ROWS) : props.height,
)
const w = computed(() =>
  props.crisp ? (h.value * 8) / INK_ROWS : (h.value * 12) / 13,
)
</script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    :viewBox="crisp ? '0 0 8 9' : '-2 -2 12 13'"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="C"
  >
    <template v-if="crisp">
    <g>
      <rect x="2" y="0" width="4" height="1" />
      <rect x="1" y="1" width="6" height="1" />
      <rect x="0" y="2" width="2" height="1" />
      <rect x="6" y="2" width="2" height="1" />
      <rect x="0" y="3" width="2" height="1" />
      <rect x="0" y="4" width="2" height="1" />
      <rect x="0" y="5" width="2" height="1" />
      <rect x="0" y="6" width="2" height="1" />
      <rect x="6" y="6" width="2" height="1" />
      <rect x="1" y="7" width="6" height="1" />
      <rect x="2" y="8" width="4" height="1" />
    </g>
    </template>
    <template v-else>
    <g opacity="1">
      <rect x="2" y="0" width="4" height="1" />
      <rect x="2" y="1" width="5" height="1" />
      <rect x="1" y="2" width="1" height="1" />
      <rect x="6" y="2" width="2" height="1" />
      <rect x="0" y="3" width="2" height="1" />
      <rect x="0" y="4" width="2" height="1" />
      <rect x="0" y="5" width="2" height="1" />
      <rect x="0" y="6" width="2" height="1" />
      <rect x="7" y="6" width="1" height="1" />
      <rect x="1" y="7" width="2" height="1" />
      <rect x="4" y="7" width="1" height="1" />
      <rect x="6" y="7" width="1" height="1" />
      <rect x="2" y="8" width="4" height="1" />
    </g>
    <g opacity="0.62">
      <rect x="1" y="1" width="1" height="1" />
      <rect x="0" y="2" width="1" height="1" />
      <rect x="6" y="6" width="1" height="1" />
      <rect x="3" y="7" width="1" height="1" />
      <rect x="5" y="7" width="1" height="1" />
    </g>
    <g opacity="0.42">
      <rect x="1" y="-1" width="1" height="1" />
      <rect x="3" y="-1" width="1" height="1" />
      <rect x="5" y="-1" width="1" height="1" />
      <rect x="0" y="0" width="1" height="1" />
      <rect x="6" y="0" width="1" height="1" />
      <rect x="-1" y="1" width="1" height="1" />
      <rect x="7" y="1" width="1" height="1" />
      <rect x="2" y="2" width="1" height="1" />
      <rect x="4" y="2" width="1" height="1" />
      <rect x="8" y="2" width="1" height="1" />
      <rect x="-1" y="3" width="1" height="1" />
      <rect x="5" y="3" width="1" height="1" />
      <rect x="7" y="3" width="1" height="1" />
      <rect x="2" y="4" width="1" height="1" />
      <rect x="-1" y="5" width="1" height="1" />
      <rect x="5" y="5" width="1" height="1" />
      <rect x="7" y="5" width="1" height="1" />
      <rect x="2" y="6" width="1" height="1" />
      <rect x="4" y="6" width="1" height="1" />
      <rect x="8" y="6" width="1" height="1" />
      <rect x="-1" y="7" width="1" height="1" />
      <rect x="7" y="7" width="1" height="1" />
      <rect x="0" y="8" width="1" height="1" />
      <rect x="6" y="8" width="1" height="1" />
      <rect x="1" y="9" width="1" height="1" />
      <rect x="3" y="9" width="1" height="1" />
      <rect x="5" y="9" width="1" height="1" />
    </g>
    <g opacity="0.15">
      <rect x="0" y="-2" width="1" height="1" />
      <rect x="2" y="-2" width="1" height="1" />
      <rect x="4" y="-2" width="1" height="1" />
      <rect x="6" y="-2" width="1" height="1" />
      <rect x="-2" y="0" width="1" height="1" />
      <rect x="8" y="0" width="1" height="1" />
      <rect x="-2" y="2" width="1" height="1" />
      <rect x="-2" y="4" width="1" height="1" />
      <rect x="4" y="4" width="1" height="1" />
      <rect x="6" y="4" width="1" height="1" />
      <rect x="8" y="4" width="1" height="1" />
      <rect x="-2" y="6" width="1" height="1" />
      <rect x="-2" y="8" width="1" height="1" />
      <rect x="8" y="8" width="1" height="1" />
      <rect x="0" y="10" width="1" height="1" />
      <rect x="2" y="10" width="1" height="1" />
      <rect x="4" y="10" width="1" height="1" />
      <rect x="6" y="10" width="1" height="1" />
    </g>
    </template>
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
</style>
