<script setup lang="ts">
import { computed } from 'vue'

/**
 * The full wordmark — used where the app introduces itself.
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this file.
 * Every pixel is a rect on a 12-row grid; the fringe is an ordered dither,
 * so the mark stays itself at 14px and at 400px.
 *
 * `crisp` drops the dither and trims to the letterform. Use it anywhere the
 * mark is small: the fringe needs three or four device pixels per grid cell to
 * read as a fringe, and below that it only softens the stroke.
 */
const props = withDefaults(defineProps<{ height?: number; crisp?: boolean }>(), {
  height: 32,
  crisp: false,
})

/* Crisp only pays off on a whole multiple of the grid — a 2px stem at a
   fractional scale lands on a half pixel and the rounding eats one side of it. */
const INK_ROWS = 12
const h = computed(() =>
  props.crisp ? Math.max(INK_ROWS, Math.round(props.height / INK_ROWS) * INK_ROWS) : props.height,
)
const w = computed(() =>
  props.crisp ? (h.value * 60) / INK_ROWS : (h.value * 64) / 16,
)
</script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    :viewBox="crisp ? '0 0 60 12' : '-2 -2 64 16'"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="Cockpit"
  >
    <template v-if="crisp">
    <g>
      <rect x="2" y="0" width="4" height="1" />
      <rect x="31" y="0" width="2" height="1" />
      <rect x="50" y="0" width="2" height="1" />
      <rect x="1" y="1" width="6" height="1" />
      <rect x="31" y="1" width="2" height="1" />
      <rect x="50" y="1" width="2" height="1" />
      <rect x="56" y="1" width="2" height="1" />
      <rect x="0" y="2" width="2" height="1" />
      <rect x="6" y="2" width="2" height="1" />
      <rect x="31" y="2" width="2" height="1" />
      <rect x="56" y="2" width="2" height="1" />
      <rect x="0" y="3" width="2" height="1" />
      <rect x="12" y="3" width="5" height="1" />
      <rect x="22" y="3" width="5" height="1" />
      <rect x="31" y="3" width="2" height="1" />
      <rect x="35" y="3" width="2" height="1" />
      <rect x="40" y="3" width="6" height="1" />
      <rect x="50" y="3" width="2" height="1" />
      <rect x="55" y="3" width="5" height="1" />
      <rect x="0" y="4" width="2" height="1" />
      <rect x="11" y="4" width="2" height="1" />
      <rect x="16" y="4" width="2" height="1" />
      <rect x="21" y="4" width="2" height="1" />
      <rect x="26" y="4" width="2" height="1" />
      <rect x="31" y="4" width="2" height="1" />
      <rect x="34" y="4" width="2" height="1" />
      <rect x="40" y="4" width="2" height="1" />
      <rect x="45" y="4" width="2" height="1" />
      <rect x="50" y="4" width="2" height="1" />
      <rect x="56" y="4" width="2" height="1" />
      <rect x="0" y="5" width="2" height="1" />
      <rect x="11" y="5" width="2" height="1" />
      <rect x="16" y="5" width="2" height="1" />
      <rect x="21" y="5" width="2" height="1" />
      <rect x="31" y="5" width="4" height="1" />
      <rect x="40" y="5" width="2" height="1" />
      <rect x="45" y="5" width="2" height="1" />
      <rect x="50" y="5" width="2" height="1" />
      <rect x="56" y="5" width="2" height="1" />
      <rect x="0" y="6" width="2" height="1" />
      <rect x="6" y="6" width="2" height="1" />
      <rect x="11" y="6" width="2" height="1" />
      <rect x="16" y="6" width="2" height="1" />
      <rect x="21" y="6" width="2" height="1" />
      <rect x="31" y="6" width="4" height="1" />
      <rect x="40" y="6" width="2" height="1" />
      <rect x="45" y="6" width="2" height="1" />
      <rect x="50" y="6" width="2" height="1" />
      <rect x="56" y="6" width="2" height="1" />
      <rect x="1" y="7" width="6" height="1" />
      <rect x="11" y="7" width="2" height="1" />
      <rect x="16" y="7" width="2" height="1" />
      <rect x="21" y="7" width="2" height="1" />
      <rect x="26" y="7" width="2" height="1" />
      <rect x="31" y="7" width="2" height="1" />
      <rect x="34" y="7" width="2" height="1" />
      <rect x="40" y="7" width="2" height="1" />
      <rect x="45" y="7" width="2" height="1" />
      <rect x="50" y="7" width="2" height="1" />
      <rect x="56" y="7" width="2" height="1" />
      <rect x="2" y="8" width="4" height="1" />
      <rect x="12" y="8" width="5" height="1" />
      <rect x="22" y="8" width="5" height="1" />
      <rect x="31" y="8" width="2" height="1" />
      <rect x="35" y="8" width="2" height="1" />
      <rect x="40" y="8" width="6" height="1" />
      <rect x="50" y="8" width="2" height="1" />
      <rect x="56" y="8" width="4" height="1" />
      <rect x="40" y="9" width="2" height="1" />
      <rect x="40" y="10" width="2" height="1" />
      <rect x="40" y="11" width="2" height="1" />
    </g>
    </template>
    <template v-else>
    <g opacity="1">
      <rect x="2" y="0" width="4" height="1" />
      <rect x="31" y="0" width="2" height="1" />
      <rect x="50" y="0" width="2" height="1" />
      <rect x="2" y="1" width="5" height="1" />
      <rect x="31" y="1" width="2" height="1" />
      <rect x="50" y="1" width="2" height="1" />
      <rect x="56" y="1" width="1" height="1" />
      <rect x="1" y="2" width="1" height="1" />
      <rect x="6" y="2" width="2" height="1" />
      <rect x="31" y="2" width="2" height="1" />
      <rect x="56" y="2" width="2" height="1" />
      <rect x="0" y="3" width="2" height="1" />
      <rect x="12" y="3" width="1" height="1" />
      <rect x="14" y="3" width="1" height="1" />
      <rect x="16" y="3" width="1" height="1" />
      <rect x="22" y="3" width="1" height="1" />
      <rect x="24" y="3" width="1" height="1" />
      <rect x="26" y="3" width="1" height="1" />
      <rect x="31" y="3" width="2" height="1" />
      <rect x="36" y="3" width="1" height="1" />
      <rect x="40" y="3" width="1" height="1" />
      <rect x="42" y="3" width="1" height="1" />
      <rect x="44" y="3" width="1" height="1" />
      <rect x="50" y="3" width="1" height="1" />
      <rect x="56" y="3" width="3" height="1" />
      <rect x="0" y="4" width="2" height="1" />
      <rect x="11" y="4" width="2" height="1" />
      <rect x="16" y="4" width="2" height="1" />
      <rect x="21" y="4" width="2" height="1" />
      <rect x="26" y="4" width="2" height="1" />
      <rect x="31" y="4" width="2" height="1" />
      <rect x="35" y="4" width="1" height="1" />
      <rect x="40" y="4" width="2" height="1" />
      <rect x="45" y="4" width="1" height="1" />
      <rect x="50" y="4" width="2" height="1" />
      <rect x="56" y="4" width="2" height="1" />
      <rect x="0" y="5" width="2" height="1" />
      <rect x="11" y="5" width="2" height="1" />
      <rect x="16" y="5" width="2" height="1" />
      <rect x="21" y="5" width="2" height="1" />
      <rect x="31" y="5" width="2" height="1" />
      <rect x="34" y="5" width="1" height="1" />
      <rect x="40" y="5" width="2" height="1" />
      <rect x="45" y="5" width="2" height="1" />
      <rect x="50" y="5" width="2" height="1" />
      <rect x="56" y="5" width="2" height="1" />
      <rect x="0" y="6" width="2" height="1" />
      <rect x="7" y="6" width="1" height="1" />
      <rect x="11" y="6" width="2" height="1" />
      <rect x="16" y="6" width="2" height="1" />
      <rect x="21" y="6" width="2" height="1" />
      <rect x="31" y="6" width="4" height="1" />
      <rect x="40" y="6" width="2" height="1" />
      <rect x="45" y="6" width="2" height="1" />
      <rect x="50" y="6" width="2" height="1" />
      <rect x="56" y="6" width="2" height="1" />
      <rect x="1" y="7" width="2" height="1" />
      <rect x="4" y="7" width="1" height="1" />
      <rect x="6" y="7" width="1" height="1" />
      <rect x="11" y="7" width="2" height="1" />
      <rect x="16" y="7" width="2" height="1" />
      <rect x="21" y="7" width="2" height="1" />
      <rect x="26" y="7" width="1" height="1" />
      <rect x="31" y="7" width="2" height="1" />
      <rect x="34" y="7" width="1" height="1" />
      <rect x="40" y="7" width="2" height="1" />
      <rect x="45" y="7" width="2" height="1" />
      <rect x="50" y="7" width="2" height="1" />
      <rect x="56" y="7" width="2" height="1" />
      <rect x="2" y="8" width="4" height="1" />
      <rect x="12" y="8" width="2" height="1" />
      <rect x="15" y="8" width="2" height="1" />
      <rect x="22" y="8" width="2" height="1" />
      <rect x="25" y="8" width="2" height="1" />
      <rect x="31" y="8" width="2" height="1" />
      <rect x="35" y="8" width="1" height="1" />
      <rect x="40" y="8" width="2" height="1" />
      <rect x="43" y="8" width="1" height="1" />
      <rect x="45" y="8" width="1" height="1" />
      <rect x="50" y="8" width="2" height="1" />
      <rect x="56" y="8" width="2" height="1" />
      <rect x="59" y="8" width="1" height="1" />
      <rect x="40" y="9" width="2" height="1" />
      <rect x="40" y="10" width="2" height="1" />
      <rect x="40" y="11" width="2" height="1" />
    </g>
    <g opacity="0.62">
      <rect x="1" y="1" width="1" height="1" />
      <rect x="57" y="1" width="1" height="1" />
      <rect x="0" y="2" width="1" height="1" />
      <rect x="13" y="3" width="1" height="1" />
      <rect x="15" y="3" width="1" height="1" />
      <rect x="23" y="3" width="1" height="1" />
      <rect x="25" y="3" width="1" height="1" />
      <rect x="35" y="3" width="1" height="1" />
      <rect x="41" y="3" width="1" height="1" />
      <rect x="43" y="3" width="1" height="1" />
      <rect x="45" y="3" width="1" height="1" />
      <rect x="51" y="3" width="1" height="1" />
      <rect x="55" y="3" width="1" height="1" />
      <rect x="59" y="3" width="1" height="1" />
      <rect x="34" y="4" width="1" height="1" />
      <rect x="46" y="4" width="1" height="1" />
      <rect x="33" y="5" width="1" height="1" />
      <rect x="6" y="6" width="1" height="1" />
      <rect x="3" y="7" width="1" height="1" />
      <rect x="5" y="7" width="1" height="1" />
      <rect x="27" y="7" width="1" height="1" />
      <rect x="35" y="7" width="1" height="1" />
      <rect x="14" y="8" width="1" height="1" />
      <rect x="24" y="8" width="1" height="1" />
      <rect x="36" y="8" width="1" height="1" />
      <rect x="42" y="8" width="1" height="1" />
      <rect x="44" y="8" width="1" height="1" />
      <rect x="58" y="8" width="1" height="1" />
    </g>
    <g opacity="0.42">
      <rect x="1" y="-1" width="1" height="1" />
      <rect x="3" y="-1" width="1" height="1" />
      <rect x="5" y="-1" width="1" height="1" />
      <rect x="31" y="-1" width="1" height="1" />
      <rect x="33" y="-1" width="1" height="1" />
      <rect x="49" y="-1" width="1" height="1" />
      <rect x="51" y="-1" width="1" height="1" />
      <rect x="0" y="0" width="1" height="1" />
      <rect x="6" y="0" width="1" height="1" />
      <rect x="30" y="0" width="1" height="1" />
      <rect x="52" y="0" width="1" height="1" />
      <rect x="56" y="0" width="1" height="1" />
      <rect x="58" y="0" width="1" height="1" />
      <rect x="-1" y="1" width="1" height="1" />
      <rect x="7" y="1" width="1" height="1" />
      <rect x="33" y="1" width="1" height="1" />
      <rect x="49" y="1" width="1" height="1" />
      <rect x="55" y="1" width="1" height="1" />
      <rect x="2" y="2" width="1" height="1" />
      <rect x="4" y="2" width="1" height="1" />
      <rect x="8" y="2" width="1" height="1" />
      <rect x="12" y="2" width="1" height="1" />
      <rect x="14" y="2" width="1" height="1" />
      <rect x="16" y="2" width="1" height="1" />
      <rect x="22" y="2" width="1" height="1" />
      <rect x="24" y="2" width="1" height="1" />
      <rect x="26" y="2" width="1" height="1" />
      <rect x="30" y="2" width="1" height="1" />
      <rect x="34" y="2" width="1" height="1" />
      <rect x="36" y="2" width="1" height="1" />
      <rect x="40" y="2" width="1" height="1" />
      <rect x="42" y="2" width="1" height="1" />
      <rect x="44" y="2" width="1" height="1" />
      <rect x="46" y="2" width="1" height="1" />
      <rect x="50" y="2" width="1" height="1" />
      <rect x="52" y="2" width="1" height="1" />
      <rect x="54" y="2" width="1" height="1" />
      <rect x="58" y="2" width="1" height="1" />
      <rect x="60" y="2" width="1" height="1" />
      <rect x="-1" y="3" width="1" height="1" />
      <rect x="5" y="3" width="1" height="1" />
      <rect x="7" y="3" width="1" height="1" />
      <rect x="11" y="3" width="1" height="1" />
      <rect x="17" y="3" width="1" height="1" />
      <rect x="21" y="3" width="1" height="1" />
      <rect x="27" y="3" width="1" height="1" />
      <rect x="33" y="3" width="1" height="1" />
      <rect x="37" y="3" width="1" height="1" />
      <rect x="39" y="3" width="1" height="1" />
      <rect x="47" y="3" width="1" height="1" />
      <rect x="49" y="3" width="1" height="1" />
      <rect x="2" y="4" width="1" height="1" />
      <rect x="10" y="4" width="1" height="1" />
      <rect x="14" y="4" width="1" height="1" />
      <rect x="18" y="4" width="1" height="1" />
      <rect x="20" y="4" width="1" height="1" />
      <rect x="24" y="4" width="1" height="1" />
      <rect x="28" y="4" width="1" height="1" />
      <rect x="30" y="4" width="1" height="1" />
      <rect x="36" y="4" width="1" height="1" />
      <rect x="42" y="4" width="1" height="1" />
      <rect x="44" y="4" width="1" height="1" />
      <rect x="52" y="4" width="1" height="1" />
      <rect x="54" y="4" width="1" height="1" />
      <rect x="58" y="4" width="1" height="1" />
      <rect x="60" y="4" width="1" height="1" />
      <rect x="-1" y="5" width="1" height="1" />
      <rect x="5" y="5" width="1" height="1" />
      <rect x="7" y="5" width="1" height="1" />
      <rect x="13" y="5" width="1" height="1" />
      <rect x="15" y="5" width="1" height="1" />
      <rect x="23" y="5" width="1" height="1" />
      <rect x="25" y="5" width="1" height="1" />
      <rect x="27" y="5" width="1" height="1" />
      <rect x="35" y="5" width="1" height="1" />
      <rect x="39" y="5" width="1" height="1" />
      <rect x="47" y="5" width="1" height="1" />
      <rect x="49" y="5" width="1" height="1" />
      <rect x="55" y="5" width="1" height="1" />
      <rect x="2" y="6" width="1" height="1" />
      <rect x="4" y="6" width="1" height="1" />
      <rect x="8" y="6" width="1" height="1" />
      <rect x="10" y="6" width="1" height="1" />
      <rect x="18" y="6" width="1" height="1" />
      <rect x="20" y="6" width="1" height="1" />
      <rect x="26" y="6" width="1" height="1" />
      <rect x="28" y="6" width="1" height="1" />
      <rect x="30" y="6" width="1" height="1" />
      <rect x="36" y="6" width="1" height="1" />
      <rect x="42" y="6" width="1" height="1" />
      <rect x="44" y="6" width="1" height="1" />
      <rect x="52" y="6" width="1" height="1" />
      <rect x="58" y="6" width="1" height="1" />
      <rect x="-1" y="7" width="1" height="1" />
      <rect x="7" y="7" width="1" height="1" />
      <rect x="13" y="7" width="1" height="1" />
      <rect x="15" y="7" width="1" height="1" />
      <rect x="23" y="7" width="1" height="1" />
      <rect x="25" y="7" width="1" height="1" />
      <rect x="33" y="7" width="1" height="1" />
      <rect x="37" y="7" width="1" height="1" />
      <rect x="39" y="7" width="1" height="1" />
      <rect x="43" y="7" width="1" height="1" />
      <rect x="47" y="7" width="1" height="1" />
      <rect x="49" y="7" width="1" height="1" />
      <rect x="55" y="7" width="1" height="1" />
      <rect x="59" y="7" width="1" height="1" />
      <rect x="0" y="8" width="1" height="1" />
      <rect x="6" y="8" width="1" height="1" />
      <rect x="10" y="8" width="1" height="1" />
      <rect x="18" y="8" width="1" height="1" />
      <rect x="20" y="8" width="1" height="1" />
      <rect x="28" y="8" width="1" height="1" />
      <rect x="30" y="8" width="1" height="1" />
      <rect x="34" y="8" width="1" height="1" />
      <rect x="46" y="8" width="1" height="1" />
      <rect x="52" y="8" width="1" height="1" />
      <rect x="60" y="8" width="1" height="1" />
      <rect x="1" y="9" width="1" height="1" />
      <rect x="3" y="9" width="1" height="1" />
      <rect x="5" y="9" width="1" height="1" />
      <rect x="11" y="9" width="1" height="1" />
      <rect x="13" y="9" width="1" height="1" />
      <rect x="15" y="9" width="1" height="1" />
      <rect x="17" y="9" width="1" height="1" />
      <rect x="21" y="9" width="1" height="1" />
      <rect x="23" y="9" width="1" height="1" />
      <rect x="25" y="9" width="1" height="1" />
      <rect x="27" y="9" width="1" height="1" />
      <rect x="31" y="9" width="1" height="1" />
      <rect x="33" y="9" width="1" height="1" />
      <rect x="35" y="9" width="1" height="1" />
      <rect x="37" y="9" width="1" height="1" />
      <rect x="39" y="9" width="1" height="1" />
      <rect x="43" y="9" width="1" height="1" />
      <rect x="45" y="9" width="1" height="1" />
      <rect x="49" y="9" width="1" height="1" />
      <rect x="51" y="9" width="1" height="1" />
      <rect x="55" y="9" width="1" height="1" />
      <rect x="57" y="9" width="1" height="1" />
      <rect x="59" y="9" width="1" height="1" />
      <rect x="42" y="10" width="1" height="1" />
      <rect x="39" y="11" width="1" height="1" />
      <rect x="40" y="12" width="1" height="1" />
      <rect x="42" y="12" width="1" height="1" />
    </g>
    <g opacity="0.15">
      <rect x="0" y="-2" width="1" height="1" />
      <rect x="2" y="-2" width="1" height="1" />
      <rect x="4" y="-2" width="1" height="1" />
      <rect x="6" y="-2" width="1" height="1" />
      <rect x="30" y="-2" width="1" height="1" />
      <rect x="32" y="-2" width="1" height="1" />
      <rect x="34" y="-2" width="1" height="1" />
      <rect x="48" y="-2" width="1" height="1" />
      <rect x="50" y="-2" width="1" height="1" />
      <rect x="52" y="-2" width="1" height="1" />
      <rect x="-2" y="0" width="1" height="1" />
      <rect x="8" y="0" width="1" height="1" />
      <rect x="34" y="0" width="1" height="1" />
      <rect x="48" y="0" width="1" height="1" />
      <rect x="54" y="0" width="1" height="1" />
      <rect x="-2" y="2" width="1" height="1" />
      <rect x="10" y="2" width="1" height="1" />
      <rect x="18" y="2" width="1" height="1" />
      <rect x="20" y="2" width="1" height="1" />
      <rect x="28" y="2" width="1" height="1" />
      <rect x="38" y="2" width="1" height="1" />
      <rect x="48" y="2" width="1" height="1" />
      <rect x="-2" y="4" width="1" height="1" />
      <rect x="4" y="4" width="1" height="1" />
      <rect x="6" y="4" width="1" height="1" />
      <rect x="8" y="4" width="1" height="1" />
      <rect x="38" y="4" width="1" height="1" />
      <rect x="48" y="4" width="1" height="1" />
      <rect x="-2" y="6" width="1" height="1" />
      <rect x="14" y="6" width="1" height="1" />
      <rect x="24" y="6" width="1" height="1" />
      <rect x="38" y="6" width="1" height="1" />
      <rect x="48" y="6" width="1" height="1" />
      <rect x="54" y="6" width="1" height="1" />
      <rect x="60" y="6" width="1" height="1" />
      <rect x="-2" y="8" width="1" height="1" />
      <rect x="8" y="8" width="1" height="1" />
      <rect x="38" y="8" width="1" height="1" />
      <rect x="48" y="8" width="1" height="1" />
      <rect x="54" y="8" width="1" height="1" />
      <rect x="0" y="10" width="1" height="1" />
      <rect x="2" y="10" width="1" height="1" />
      <rect x="4" y="10" width="1" height="1" />
      <rect x="6" y="10" width="1" height="1" />
      <rect x="10" y="10" width="1" height="1" />
      <rect x="12" y="10" width="1" height="1" />
      <rect x="14" y="10" width="1" height="1" />
      <rect x="16" y="10" width="1" height="1" />
      <rect x="18" y="10" width="1" height="1" />
      <rect x="20" y="10" width="1" height="1" />
      <rect x="22" y="10" width="1" height="1" />
      <rect x="24" y="10" width="1" height="1" />
      <rect x="26" y="10" width="1" height="1" />
      <rect x="28" y="10" width="1" height="1" />
      <rect x="30" y="10" width="1" height="1" />
      <rect x="32" y="10" width="1" height="1" />
      <rect x="34" y="10" width="1" height="1" />
      <rect x="36" y="10" width="1" height="1" />
      <rect x="38" y="10" width="1" height="1" />
      <rect x="44" y="10" width="1" height="1" />
      <rect x="46" y="10" width="1" height="1" />
      <rect x="48" y="10" width="1" height="1" />
      <rect x="50" y="10" width="1" height="1" />
      <rect x="52" y="10" width="1" height="1" />
      <rect x="54" y="10" width="1" height="1" />
      <rect x="56" y="10" width="1" height="1" />
      <rect x="58" y="10" width="1" height="1" />
      <rect x="60" y="10" width="1" height="1" />
      <rect x="38" y="12" width="1" height="1" />
    </g>
    </template>
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
</style>
