<script setup lang="ts">
import { computed } from 'vue'

/**
 * The full wordmark — used where the app introduces itself.
 *
 * Generated by apps/desktop/scripts/logo.mjs — edit the generator, not this
 * file. Every pixel is a rect on a 12-row grid, so the mark has one
 * silhouette at 18px and at 400px rather than a shape that dissolves as it
 * shrinks.
 *
 * The first letter is its own ink. It follows `currentColor` like the rest
 * until a placement sets `--wm-lead` — the two-tone wordmark is opt-in, so
 * the mark never arrives tinted somewhere it was only meant to be text.
 */
const props = withDefaults(defineProps<{ height?: number }>(), { height: 36 })

/* Snapped to a whole multiple of the grid. A 2px stem at a fractional scale
   lands on a half pixel and the rounding eats one side of it — which is the
   difference between a pixel mark and a blurred one. */
const GRID = 12
const h = computed(() => Math.max(GRID, Math.round(props.height / GRID) * GRID))
const w = computed(() => (h.value * 75) / GRID)
</script>

<template>
  <svg
    class="brand"
    :height="h"
    :width="w"
    viewBox="0 0 75 12"
    fill="currentColor"
    shape-rendering="crispEdges"
    role="img"
    aria-label="COCKPIT"
  >
    <g class="lead">
      <rect x="1" y="0" width="7" height="1" />
      <rect x="0" y="1" width="9" height="1" />
      <rect x="0" y="2" width="9" height="1" />
      <rect x="0" y="3" width="4" height="1" />
      <rect x="0" y="4" width="3" height="1" />
      <rect x="0" y="5" width="3" height="1" />
      <rect x="0" y="6" width="3" height="1" />
      <rect x="0" y="7" width="3" height="1" />
      <rect x="0" y="8" width="4" height="1" />
      <rect x="0" y="9" width="9" height="1" />
      <rect x="0" y="10" width="9" height="1" />
      <rect x="1" y="11" width="7" height="1" />
    </g>
    <g class="ink">
      <rect x="12" y="0" width="7" height="1" />
      <rect x="23" y="0" width="7" height="1" />
      <rect x="34" y="0" width="2" height="1" />
      <rect x="39" y="0" width="2" height="1" />
      <rect x="45" y="0" width="7" height="1" />
      <rect x="56" y="0" width="7" height="1" />
      <rect x="67" y="0" width="7" height="1" />
      <rect x="11" y="1" width="9" height="1" />
      <rect x="22" y="1" width="9" height="1" />
      <rect x="33" y="1" width="3" height="1" />
      <rect x="39" y="1" width="3" height="1" />
      <rect x="44" y="1" width="9" height="1" />
      <rect x="55" y="1" width="9" height="1" />
      <rect x="66" y="1" width="9" height="1" />
      <rect x="11" y="2" width="9" height="1" />
      <rect x="22" y="2" width="9" height="1" />
      <rect x="33" y="2" width="3" height="1" />
      <rect x="38" y="2" width="3" height="1" />
      <rect x="44" y="2" width="9" height="1" />
      <rect x="55" y="2" width="9" height="1" />
      <rect x="66" y="2" width="9" height="1" />
      <rect x="11" y="3" width="3" height="1" />
      <rect x="17" y="3" width="3" height="1" />
      <rect x="22" y="3" width="4" height="1" />
      <rect x="33" y="3" width="3" height="1" />
      <rect x="37" y="3" width="3" height="1" />
      <rect x="44" y="3" width="3" height="1" />
      <rect x="50" y="3" width="3" height="1" />
      <rect x="58" y="3" width="3" height="1" />
      <rect x="69" y="3" width="3" height="1" />
      <rect x="11" y="4" width="3" height="1" />
      <rect x="17" y="4" width="3" height="1" />
      <rect x="22" y="4" width="3" height="1" />
      <rect x="33" y="4" width="6" height="1" />
      <rect x="44" y="4" width="3" height="1" />
      <rect x="50" y="4" width="3" height="1" />
      <rect x="58" y="4" width="3" height="1" />
      <rect x="69" y="4" width="3" height="1" />
      <rect x="11" y="5" width="3" height="1" />
      <rect x="17" y="5" width="3" height="1" />
      <rect x="22" y="5" width="3" height="1" />
      <rect x="33" y="5" width="6" height="1" />
      <rect x="44" y="5" width="3" height="1" />
      <rect x="50" y="5" width="3" height="1" />
      <rect x="58" y="5" width="3" height="1" />
      <rect x="69" y="5" width="3" height="1" />
      <rect x="11" y="6" width="3" height="1" />
      <rect x="17" y="6" width="3" height="1" />
      <rect x="22" y="6" width="3" height="1" />
      <rect x="33" y="6" width="6" height="1" />
      <rect x="44" y="6" width="9" height="1" />
      <rect x="58" y="6" width="3" height="1" />
      <rect x="69" y="6" width="3" height="1" />
      <rect x="11" y="7" width="3" height="1" />
      <rect x="17" y="7" width="3" height="1" />
      <rect x="22" y="7" width="3" height="1" />
      <rect x="33" y="7" width="6" height="1" />
      <rect x="44" y="7" width="9" height="1" />
      <rect x="58" y="7" width="3" height="1" />
      <rect x="69" y="7" width="3" height="1" />
      <rect x="11" y="8" width="3" height="1" />
      <rect x="17" y="8" width="3" height="1" />
      <rect x="22" y="8" width="4" height="1" />
      <rect x="33" y="8" width="3" height="1" />
      <rect x="37" y="8" width="3" height="1" />
      <rect x="44" y="8" width="9" height="1" />
      <rect x="58" y="8" width="3" height="1" />
      <rect x="69" y="8" width="3" height="1" />
      <rect x="11" y="9" width="9" height="1" />
      <rect x="22" y="9" width="9" height="1" />
      <rect x="33" y="9" width="3" height="1" />
      <rect x="38" y="9" width="3" height="1" />
      <rect x="44" y="9" width="3" height="1" />
      <rect x="55" y="9" width="9" height="1" />
      <rect x="69" y="9" width="3" height="1" />
      <rect x="11" y="10" width="9" height="1" />
      <rect x="22" y="10" width="9" height="1" />
      <rect x="33" y="10" width="3" height="1" />
      <rect x="39" y="10" width="3" height="1" />
      <rect x="44" y="10" width="3" height="1" />
      <rect x="55" y="10" width="9" height="1" />
      <rect x="69" y="10" width="3" height="1" />
      <rect x="12" y="11" width="7" height="1" />
      <rect x="23" y="11" width="7" height="1" />
      <rect x="34" y="11" width="2" height="1" />
      <rect x="39" y="11" width="2" height="1" />
      <rect x="45" y="11" width="2" height="1" />
      <rect x="56" y="11" width="7" height="1" />
      <rect x="69" y="11" width="3" height="1" />
    </g>
  </svg>
</template>

<style scoped>
.brand {
  display: block;
  flex: none;
}
.lead {
  fill: var(--wm-lead, currentColor);
}
</style>
